apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      name: fastapi
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: mrcsz/fastapi:latest
          ports:
            - containerPort: 80
          # envFrom:
          #   - configMapRef:
          #       name: portal-configmap
          resources:
            limits:
              memory: 128Mi
              cpu: "0.2"
            requests:
              cpu: "0.1"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   periodSeconds: 10
          #   failureThreshold: 3
          #   initialDelaySeconds: 20
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   periodSeconds: 10
          #   failureThreshold: 5
          #   initialDelaySeconds: 3
            